name: sinagod

on:
 schedule:
   - cron: '26 */2 * * *'
 workflow_dispatch:
 watch:
   types: started
 repository_dispatch:
   types: sinagod

jobs:
  mirror:
    env:
      PAT: ${{ secrets.PAT }}
      
      DEFAULT_DST: github/sinagod
      DEFAULT_RENAME_FMT: 's/(.*)/${SRC_TYPE}_${SRC_ACCOUNT}_\1/g'
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id 

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: | 
            "${{ github.workspace }}/.cache"
          key: ${{ runner.os }}-cache-actions
          restore-keys: |
            ${{ runner.os }}-cache-actions
      
      - name: mirror github/adwktt
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/adwktt
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.SINA_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.SINA_GITHUB_TOKEN }}
          static_list: "adwktt,test"
          dst_account_type: user
#           force_update: true
          rename_dst: true
          # clone_style: https
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: sync github -> gitee
        uses: Yikun/hub-mirror-action@master
        if: env.dst_key
        with:
          src: github/sinagod
          dst: gitee/the_king_god
          static_list: "github_adwktt_adwktt,github_adwktt_test"
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
