name: New-Sina

on:
 schedule:
   - cron: '35 */2 * * *'
 workflow_dispatch:
 watch:
   types: started
 repository_dispatch:
   types: New-Sina

jobs:
  mirror:
    env:
      PAT: ${{ secrets.PAT }}
      DEFAULT_DST: github/New-Sina
      DEFAULT_RENAME_FMT: 's/(.*)/${SRC_TYPE}_${SRC_ACCOUNT}_\1/g'
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: | 
            "${{ github.workspace }}/.cache"
          key: ${{ runner.os }}-cache-actions
          restore-keys: |
            ${{ runner.os }}-cache-actions

#       - name: mirror github/ziye12
#         uses: fakedon/hub-mirror-action@fakedon
#         with:
#           src: github/ziye12
#           dst: ${{ env.DEFAULT_DST }}
#           dst_key: ${{ secrets.NSINA_GITHUB_SSH_KEY }}
#           dst_token: ${{ secrets.NSINA_GITHUB_TOKEN }}
#           static_list: "JavaScript"
#           dst_account_type: user
# #           force_update: true
#           rename_dst: true
#           # clone_style: https
#           rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

#       - name: mirror gitee/lxk0301
#         uses: fakedon/hub-mirror-action@fakedon
#         with:
#           src: gitee/lxk0301
#           dst: ${{ env.DEFAULT_DST }}
#           dst_key: ${{ secrets.NSINA_GITHUB_SSH_KEY }}
#           dst_token: ${{ secrets.NSINA_GITHUB_TOKEN }}
#           static_list: "updateTeam,jd_scripts"
#           dst_account_type: user
# #           force_update: true
#           rename_dst: true
#           # clone_style: https
#           rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/pxylen
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/pxylen
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.NSINA_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.NSINA_GITHUB_TOKEN }}
          static_list: "dog_jd,abc_"
          dst_account_type: user
          force_update: true
          rename_dst: true
          # clone_style: https
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}
  
      - name: mirror github/whyour
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/whyour
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.NSINA_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.NSINA_GITHUB_TOKEN }}
          static_list: "hundun"
          dst_account_type: user
          force_update: true
          rename_dst: true
          # clone_style: https
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}
      
#       - name: mirror github/MicrosoftCorp12
#         uses: fakedon/hub-mirror-action@fakedon
#         with:
#           src: github/MicrosoftCorp12
#           dst: ${{ env.DEFAULT_DST }}
#           dst_key: ${{ secrets.NSINA_GITHUB_SSH_KEY }}
#           dst_token: ${{ secrets.NSINA_GITHUB_TOKEN }}
#           static_list: "chedui"
#           dst_account_type: user
#           force_update: true
#           rename_dst: true
#           # clone_style: https
#           rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}
   
#       - name: mirror github/Username-ios
#         uses: fakedon/hub-mirror-action@fakedon
#         with:
#           src: github/dajijiyangmao
#           dst: ${{ env.DEFAULT_DST }}
#           dst_key: ${{ secrets.NSINA_GITHUB_SSH_KEY }}
#           dst_token: ${{ secrets.NSINA_GITHUB_TOKEN }}
#           static_list: "HAOYANGMAO"
#           dst_account_type: user
#           force_update: true
#           rename_dst: true
#           # clone_style: https
#           rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}
   
      
      - name: mirror github/ztxtop
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/ztxtop
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.NSINA_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.NSINA_GITHUB_TOKEN }}
          static_list: "x"
          dst_account_type: user
          force_update: true
          rename_dst: true
          # clone_style: https
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}
          
     
      - name: mirror github/ziye66666
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/ziye66666
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.NSINA_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.NSINA_GITHUB_TOKEN }}
          static_list: "JavaScript"
          dst_account_type: user
          force_update: true
          rename_dst: true
          # clone_style: https
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}
 

#       - name: mirror github/dongguaku
#         uses: fakedon/hub-mirror-action@fakedon
#         with:
#           src: github/dongguaku
#           dst: ${{ env.DEFAULT_DST }}
#           dst_key: ${{ secrets.NSINA_GITHUB_SSH_KEY }}
#           dst_token: ${{ secrets.NSINA_GITHUB_TOKEN }}
#           static_list: "dadonghua"
#           dst_account_type: user
#           force_update: true
#           rename_dst: true
#           # clone_style: https
#           rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}


#        - name: mirror github/age174
#         uses: fakedon/hub-mirror-action@fakedon
#         with:
#           src: github/age174
#           dst: ${{ env.DEFAULT_DST }}
#           dst_key: ${{ secrets.NSINA_GITHUB_SSH_KEY }}
#           dst_token: ${{ secrets.NSINA_GITHUB_TOKEN }}
#           static_list: "-"
#           dst_account_type: user
# #           force_update: true
#           rename_dst: true
#           # clone_style: https
#           rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}





#       - name: mirror github/nzw9314
#         uses: fakedon/hub-mirror-action@fakedon
#         with:
#           src: github/nzw9314
#           dst: ${{ env.DEFAULT_DST }}
#           dst_key: ${{ secrets.NSINA_GITHUB_SSH_KEY }}
#           dst_token: ${{ secrets.NSINA_GITHUB_TOKEN }}
#           static_list: "QuantumultX,Loon,Surge"
#           dst_account_type: user
#           force_update: true
#           rename_dst: true
#           # clone_style: https
#           rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}


#       - name: mirror github/w37fhy
#         uses: fakedon/hub-mirror-action@fakedon
#         with:
#           src: github/w37fhy
#           dst: ${{ env.DEFAULT_DST }}
#           dst_key: ${{ secrets.NSINA_GITHUB_SSH_KEY }}
#           dst_token: ${{ secrets.NSINA_GITHUB_TOKEN }}
#           static_list: "QuantumultX"
#           dst_account_type: user
#           force_update: true
#           rename_dst: true
#           # clone_style: https
#           rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}


#       - name: mirror github/myouhi
#         uses: fakedon/hub-mirror-action@fakedon
#         with:
#           src: github/myouhi
#           dst: ${{ env.DEFAULT_DST }}
#           dst_key: ${{ secrets.NSINA_GITHUB_SSH_KEY }}
#           dst_token: ${{ secrets.NSINA_GITHUB_TOKEN }}
#           static_list: "QuantumultX"
#           dst_account_type: user
#           force_update: true
#           rename_dst: true
#           # clone_style: https
#           rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}


#        - name: mirror github/age174
#         uses: fakedon/hub-mirror-action@fakedon
#         with:
#           src: github/age174
#           dst: ${{ env.DEFAULT_DST }}
#           dst_key: ${{ secrets.NSINA_GITHUB_SSH_KEY }}
#           dst_token: ${{ secrets.NSINA_GITHUB_TOKEN }}
#           static_list: "-"
#           dst_account_type: user
# #           force_update: true
#           rename_dst: true
#           # clone_style: https
#           rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}
          
        
   
   
   
   
   
   










