name: xingren2020

on:
 schedule:
   - cron: '46 */2 * * *'
 workflow_dispatch:
 watch:
   types: started
 repository_dispatch:
   types: xingren2020

jobs:
  mirror:
    env:
      PAT: ${{ secrets.PAT }}
      DEFAULT_DST: github/xingren2020
      DEFAULT_RENAME_FMT: 's/(.*)/${SRC_TYPE}_${SRC_ACCOUNT}_\1/g'
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id 

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: | 
            "${{ github.workspace }}/.cache"
          key: ${{ runner.os }}-cache-actions
          restore-keys: |
            ${{ runner.os }}-cache-actions

      - name: mirror github/LXK9301
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/LXK9301
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "jd_scripts,updateTeam"
          dst_account_type: user
#           force_update: true
          rename_dst: true
          # clone_style: https
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/Zero-S1
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/Zero-S1
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "xmly_speed,JD_tools"
          dst_account_type: user
#           force_update: true
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}
      
      - name: mirror github/adwktt
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/adwktt
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "adwktt,test"
          dst_account_type: user
#           force_update: true
          rename_dst: true
          # clone_style: https
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/myouhi
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/myouhi
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "QuantumultX,QuantumultX-1"
          dst_account_type: user
#           force_update: true
          rename_dst: true
          # clone_style: https
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/YM1099
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/YM1099
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "Actions_checkin"
          dst_account_type: user
#           force_update: true
          rename_dst: true
          # clone_style: https
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/moposmall
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/moposmall
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "Script"
          dst_account_type: user
#           force_update: true
          rename_dst: true
          # clone_style: https
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/Sam139
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/Sam139
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "Myself,jd_scripts-1"
          dst_account_type: user
#           force_update: true
          rename_dst: true
          # clone_style: https
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/SamWu129
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/SamWu129
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "Js202012,webhook_execute,Py202012"
          dst_account_type: user
#           force_update: true
          rename_dst: true
          # clone_style: https
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/Sitoi
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/Sitoi
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "dailycheckin"
          dst_account_type: user
          force_update: true
          rename_dst: true
          # clone_style: https
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/jd1994527314
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/jd1994527314
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "iosrule,iosrule2021"
          dst_account_type: user
#           force_update: true
          rename_dst: true
          # clone_style: https
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/1518936683
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/1518936683
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "hub"
          dst_account_type: user
#           force_update: true
          rename_dst: true
          # clone_style: https
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/wangdelu2020
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/wangdelu2020
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "hongliyu,python"
          dst_account_type: user
#           force_update: true
          rename_dst: true
          # clone_style: https
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/iosrule-hub
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/iosrule-hub
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "iosrule2021"
          dst_account_type: user
#           force_update: true
          rename_dst: true
          # clone_style: https
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/andyzys
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/andyzys
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "jd_seckill"
          dst_account_type: user
#           force_update: true
          rename_dst: true
          # clone_style: https
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}






















